# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(739, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(731, 587))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 2000))
        self.scrollArea.setSizeIncrement(QtCore.QSize(0, 0))
        self.scrollArea.setBaseSize(QtCore.QSize(0, 0))
        self.scrollArea.setToolTipDuration(0)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -1050, 732, 1665))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox.setGeometry(QtCore.QRect(200, 160, 91, 20))
        self.checkBox.setObjectName("checkBox")
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(260, 90, 171, 21))
        self.label_10.setObjectName("label_10")
        self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_5.setGeometry(QtCore.QRect(400, 50, 81, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.grz = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.grz.setGeometry(QtCore.QRect(40, 160, 131, 22))
        self.grz.setObjectName("grz")
        self.checkBox_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_4.setGeometry(QtCore.QRect(280, 50, 91, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(10, 160, 21, 16))
        self.label.setObjectName("label")
        self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_6.setGeometry(QtCore.QRect(500, 50, 81, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.car_data = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.car_data.setEnabled(True)
        self.car_data.setGeometry(QtCore.QRect(0, 190, 737, 125))
        self.car_data.setStyleSheet("")
        self.car_data.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.car_data.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car_data.setProperty("frame.hide()", "")
        self.car_data.setObjectName("car_data")
        self.car_model = QtWidgets.QLineEdit(self.car_data)
        self.car_model.setGeometry(QtCore.QRect(12, 35, 137, 24))
        self.car_model.setObjectName("car_model")
        self.car_year = QtWidgets.QLineEdit(self.car_data)
        self.car_year.setGeometry(QtCore.QRect(156, 35, 137, 24))
        self.car_year.setObjectName("car_year")
        self.car_mark = QtWidgets.QLineEdit(self.car_data)
        self.car_mark.setGeometry(QtCore.QRect(300, 35, 137, 24))
        self.car_mark.setObjectName("car_mark")
        self.label_12 = QtWidgets.QLabel(self.car_data)
        self.label_12.setGeometry(QtCore.QRect(12, 12, 45, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.car_data)
        self.label_13.setGeometry(QtCore.QRect(156, 12, 73, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.car_data)
        self.label_14.setGeometry(QtCore.QRect(300, 12, 37, 16))
        self.label_14.setObjectName("label_14")
        self.car_vin = QtWidgets.QLineEdit(self.car_data)
        self.car_vin.setGeometry(QtCore.QRect(444, 35, 137, 24))
        self.car_vin.setObjectName("car_vin")
        self.label_16 = QtWidgets.QLabel(self.car_data)
        self.label_16.setGeometry(QtCore.QRect(444, 12, 20, 16))
        self.label_16.setObjectName("label_16")
        self.car_power = QtWidgets.QLineEdit(self.car_data)
        self.car_power.setGeometry(QtCore.QRect(588, 35, 81, 24))
        self.car_power.setObjectName("car_power")
        self.label_17 = QtWidgets.QLabel(self.car_data)
        self.label_17.setGeometry(QtCore.QRect(588, 12, 100, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.car_data)
        self.label_18.setGeometry(QtCore.QRect(12, 66, 33, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.car_data)
        self.label_19.setGeometry(QtCore.QRect(156, 66, 48, 16))
        self.label_19.setObjectName("label_19")
        self.car_transmission_type = QtWidgets.QComboBox(self.car_data)
        self.car_transmission_type.setGeometry(QtCore.QRect(156, 90, 126, 22))
        self.car_transmission_type.setObjectName("car_transmission_type")
        self.car_transmission_type.addItem("")
        self.car_transmission_type.addItem("")
        self.car_body_type = QtWidgets.QComboBox(self.car_data)
        self.car_body_type.setGeometry(QtCore.QRect(12, 90, 110, 22))
        self.car_body_type.setObjectName("car_body_type")
        self.car_body_type.addItem("")
        self.car_body_type.addItem("")
        self.car_body_type.addItem("")
        self.car_body_type.addItem("")
        self.car_body_type.addItem("")
        self.car_engine_type = QtWidgets.QComboBox(self.car_data)
        self.car_engine_type.setGeometry(QtCore.QRect(300, 90, 73, 22))
        self.car_engine_type.setObjectName("car_engine_type")
        self.car_engine_type.addItem("")
        self.car_engine_type.addItem("")
        self.label_20 = QtWidgets.QLabel(self.car_data)
        self.label_20.setGeometry(QtCore.QRect(300, 66, 86, 16))
        self.label_20.setObjectName("label_20")
        self.car_exploitation_date = QtWidgets.QLineEdit(self.car_data)
        self.car_exploitation_date.setGeometry(QtCore.QRect(444, 89, 137, 24))
        self.car_exploitation_date.setObjectName("car_exploitation_date")
        self.label_24 = QtWidgets.QLabel(self.car_data)
        self.label_24.setGeometry(QtCore.QRect(393, 66, 156, 16))
        self.label_24.setObjectName("label_24")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 131, 21))
        self.label_11.setObjectName("label_11")
        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 50, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(280, 10, 141, 16))
        self.label_9.setObjectName("label_9")
        self.driver1_data = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.driver1_data.setGeometry(QtCore.QRect(10, 300, 671, 231))
        self.driver1_data.setStyleSheet("")
        self.driver1_data.setObjectName("driver1_data")
        self.driver1_owner = QtWidgets.QCheckBox(self.driver1_data)
        self.driver1_owner.setGeometry(QtCore.QRect(260, 170, 181, 20))
        self.driver1_owner.setObjectName("driver1_owner")
        self.label_2 = QtWidgets.QLabel(self.driver1_data)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.driver1_data)
        self.label_5.setGeometry(QtCore.QRect(190, 120, 31, 20))
        self.label_5.setObjectName("label_5")
        self.driver1_middle_name = QtWidgets.QLineEdit(self.driver1_data)
        self.driver1_middle_name.setGeometry(QtCore.QRect(290, 90, 131, 22))
        self.driver1_middle_name.setObjectName("driver1_middle_name")
        self.label_6 = QtWidgets.QLabel(self.driver1_data)
        self.label_6.setGeometry(QtCore.QRect(330, 70, 55, 21))
        self.label_6.setObjectName("label_6")
        self.driver1_birthday_date = QtWidgets.QLineEdit(self.driver1_data)
        self.driver1_birthday_date.setGeometry(QtCore.QRect(0, 140, 131, 22))
        self.driver1_birthday_date.setObjectName("driver1_birthday_date")
        self.driver1_last_name = QtWidgets.QLineEdit(self.driver1_data)
        self.driver1_last_name.setGeometry(QtCore.QRect(0, 90, 131, 22))
        self.driver1_last_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.driver1_last_name.setObjectName("driver1_last_name")
        self.label_3 = QtWidgets.QLabel(self.driver1_data)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 21, 20))
        self.label_3.setObjectName("label_3")
        self.driver1_insured = QtWidgets.QCheckBox(self.driver1_data)
        self.driver1_insured.setGeometry(QtCore.QRect(20, 170, 181, 20))
        self.driver1_insured.setObjectName("driver1_insured")
        self.driver1_driver_age = QtWidgets.QLineEdit(self.driver1_data)
        self.driver1_driver_age.setGeometry(QtCore.QRect(140, 140, 131, 22))
        self.driver1_driver_age.setObjectName("driver1_driver_age")
        self.label_4 = QtWidgets.QLabel(self.driver1_data)
        self.label_4.setGeometry(QtCore.QRect(190, 70, 31, 20))
        self.label_4.setObjectName("label_4")
        self.driver1_main_name = QtWidgets.QLineEdit(self.driver1_data)
        self.driver1_main_name.setGeometry(QtCore.QRect(140, 90, 131, 22))
        self.driver1_main_name.setObjectName("driver1_main_name")
        self.driver1_text_tip = QtWidgets.QTextBrowser(self.driver1_data)
        self.driver1_text_tip.setGeometry(QtCore.QRect(0, 30, 81, 31))
        self.driver1_text_tip.setObjectName("driver1_text_tip")
        self.driver1_child = QtWidgets.QComboBox(self.driver1_data)
        self.driver1_child.setGeometry(QtCore.QRect(290, 140, 131, 22))
        self.driver1_child.setObjectName("driver1_child")
        self.driver1_child.addItem("")
        self.driver1_child.addItem("")
        self.label_21 = QtWidgets.QLabel(self.driver1_data)
        self.label_21.setGeometry(QtCore.QRect(340, 120, 41, 16))
        self.label_21.setObjectName("label_21")
        self.driver1_status = QtWidgets.QComboBox(self.driver1_data)
        self.driver1_status.setGeometry(QtCore.QRect(450, 90, 131, 22))
        self.driver1_status.setObjectName("driver1_status")
        self.driver1_status.addItem("")
        self.driver1_status.addItem("")
        self.label_22 = QtWidgets.QLabel(self.driver1_data)
        self.label_22.setGeometry(QtCore.QRect(470, 70, 101, 16))
        self.label_22.setObjectName("label_22")
        self.driver1_license_number = QtWidgets.QLineEdit(self.driver1_data)
        self.driver1_license_number.setGeometry(QtCore.QRect(430, 140, 71, 22))
        self.driver1_license_number.setObjectName("driver1_license_number")
        self.driver1_license_series = QtWidgets.QLineEdit(self.driver1_data)
        self.driver1_license_series.setGeometry(QtCore.QRect(520, 140, 101, 22))
        self.driver1_license_series.setObjectName("driver1_license_series")
        self.label_23 = QtWidgets.QLabel(self.driver1_data)
        self.label_23.setGeometry(QtCore.QRect(460, 120, 111, 16))
        self.label_23.setObjectName("label_23")
        self.label_15 = QtWidgets.QLabel(self.driver1_data)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 131, 21))
        self.label_15.setObjectName("label_15")
        self.driver2_add_box = QtWidgets.QCheckBox(self.driver1_data)
        self.driver2_add_box.setGeometry(QtCore.QRect(0, 200, 211, 20))
        self.driver2_add_box.setObjectName("driver2_add_box")
        self.checkBox_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_3.setGeometry(QtCore.QRect(160, 50, 91, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.driver2_data = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.driver2_data.setEnabled(False)
        self.driver2_data.setGeometry(QtCore.QRect(10, 530, 671, 231))
        self.driver2_data.setStyleSheet("")
        self.driver2_data.setObjectName("driver2_data")
        self.driver2_owner = QtWidgets.QCheckBox(self.driver2_data)
        self.driver2_owner.setGeometry(QtCore.QRect(260, 140, 181, 20))
        self.driver2_owner.setObjectName("driver2_owner")
        self.label_25 = QtWidgets.QLabel(self.driver2_data)
        self.label_25.setGeometry(QtCore.QRect(40, 40, 61, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.driver2_data)
        self.label_26.setGeometry(QtCore.QRect(190, 90, 31, 20))
        self.label_26.setObjectName("label_26")
        self.driver2_middle_name = QtWidgets.QLineEdit(self.driver2_data)
        self.driver2_middle_name.setGeometry(QtCore.QRect(290, 60, 131, 22))
        self.driver2_middle_name.setObjectName("driver2_middle_name")
        self.label_27 = QtWidgets.QLabel(self.driver2_data)
        self.label_27.setGeometry(QtCore.QRect(330, 40, 55, 21))
        self.label_27.setObjectName("label_27")
        self.driver2_birthday_date = QtWidgets.QLineEdit(self.driver2_data)
        self.driver2_birthday_date.setGeometry(QtCore.QRect(0, 110, 131, 22))
        self.driver2_birthday_date.setObjectName("driver2_birthday_date")
        self.driver2_last_name = QtWidgets.QLineEdit(self.driver2_data)
        self.driver2_last_name.setGeometry(QtCore.QRect(0, 60, 131, 22))
        self.driver2_last_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.driver2_last_name.setObjectName("driver2_last_name")
        self.label_28 = QtWidgets.QLabel(self.driver2_data)
        self.label_28.setGeometry(QtCore.QRect(50, 90, 21, 20))
        self.label_28.setObjectName("label_28")
        self.driver2_insured = QtWidgets.QCheckBox(self.driver2_data)
        self.driver2_insured.setGeometry(QtCore.QRect(20, 140, 181, 20))
        self.driver2_insured.setObjectName("driver2_insured")
        self.driver2_driver_age = QtWidgets.QLineEdit(self.driver2_data)
        self.driver2_driver_age.setGeometry(QtCore.QRect(140, 110, 131, 22))
        self.driver2_driver_age.setObjectName("driver2_driver_age")
        self.label_29 = QtWidgets.QLabel(self.driver2_data)
        self.label_29.setGeometry(QtCore.QRect(190, 40, 31, 20))
        self.label_29.setObjectName("label_29")
        self.driver2_main_name = QtWidgets.QLineEdit(self.driver2_data)
        self.driver2_main_name.setGeometry(QtCore.QRect(140, 60, 131, 22))
        self.driver2_main_name.setObjectName("driver2_main_name")
        self.driver2_text_tip = QtWidgets.QTextBrowser(self.driver2_data)
        self.driver2_text_tip.setGeometry(QtCore.QRect(0, 0, 81, 31))
        self.driver2_text_tip.setObjectName("driver2_text_tip")
        self.driver2_child = QtWidgets.QComboBox(self.driver2_data)
        self.driver2_child.setGeometry(QtCore.QRect(290, 110, 131, 22))
        self.driver2_child.setObjectName("driver2_child")
        self.driver2_child.addItem("")
        self.driver2_child.addItem("")
        self.label_30 = QtWidgets.QLabel(self.driver2_data)
        self.label_30.setGeometry(QtCore.QRect(340, 90, 41, 16))
        self.label_30.setObjectName("label_30")
        self.driver2_status = QtWidgets.QComboBox(self.driver2_data)
        self.driver2_status.setGeometry(QtCore.QRect(450, 60, 131, 22))
        self.driver2_status.setObjectName("driver2_status")
        self.driver2_status.addItem("")
        self.driver2_status.addItem("")
        self.label_31 = QtWidgets.QLabel(self.driver2_data)
        self.label_31.setGeometry(QtCore.QRect(470, 40, 101, 16))
        self.label_31.setObjectName("label_31")
        self.driver2_license_number = QtWidgets.QLineEdit(self.driver2_data)
        self.driver2_license_number.setGeometry(QtCore.QRect(430, 110, 71, 22))
        self.driver2_license_number.setObjectName("driver2_license_number")
        self.driver2_license_series2 = QtWidgets.QLineEdit(self.driver2_data)
        self.driver2_license_series2.setGeometry(QtCore.QRect(520, 110, 101, 22))
        self.driver2_license_series2.setObjectName("driver2_license_series2")
        self.label_32 = QtWidgets.QLabel(self.driver2_data)
        self.label_32.setGeometry(QtCore.QRect(460, 90, 111, 16))
        self.label_32.setObjectName("label_32")
        self.driver3_data = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.driver3_data.setEnabled(False)
        self.driver3_data.setGeometry(QtCore.QRect(10, 800, 671, 221))
        self.driver3_data.setStyleSheet("")
        self.driver3_data.setObjectName("driver3_data")
        self.driver3_owner_3 = QtWidgets.QCheckBox(self.driver3_data)
        self.driver3_owner_3.setGeometry(QtCore.QRect(260, 140, 181, 20))
        self.driver3_owner_3.setObjectName("driver3_owner_3")
        self.search_cl = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.search_cl.setGeometry(QtCore.QRect(0, 0, 111, 28))
        self.search_cl.setObjectName("search_cl")
        self.label_34 = QtWidgets.QLabel(self.driver3_data)
        self.label_34.setGeometry(QtCore.QRect(40, 40, 61, 16))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.driver3_data)
        self.label_35.setGeometry(QtCore.QRect(190, 90, 31, 20))
        self.label_35.setObjectName("label_35")
        self.driver3_middle_name = QtWidgets.QLineEdit(self.driver3_data)
        self.driver3_middle_name.setGeometry(QtCore.QRect(290, 60, 131, 22))
        self.driver3_middle_name.setObjectName("driver3_middle_name")
        self.label_36 = QtWidgets.QLabel(self.driver3_data)
        self.label_36.setGeometry(QtCore.QRect(330, 40, 55, 21))
        self.label_36.setObjectName("label_36")
        self.driver3_birthday_date = QtWidgets.QLineEdit(self.driver3_data)
        self.driver3_birthday_date.setGeometry(QtCore.QRect(0, 110, 131, 22))
        self.driver3_birthday_date.setObjectName("driver3_birthday_date")
        self.driver3_last_name = QtWidgets.QLineEdit(self.driver3_data)
        self.driver3_last_name.setGeometry(QtCore.QRect(0, 60, 131, 22))
        self.driver3_last_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.driver3_last_name.setObjectName("driver3_last_name")
        self.label_37 = QtWidgets.QLabel(self.driver3_data)
        self.label_37.setGeometry(QtCore.QRect(50, 90, 21, 20))
        self.label_37.setObjectName("label_37")
        self.driver3_insured = QtWidgets.QCheckBox(self.driver3_data)
        self.driver3_insured.setGeometry(QtCore.QRect(20, 140, 181, 20))
        self.driver3_insured.setObjectName("driver3_insured")
        self.driver3_driver_age = QtWidgets.QLineEdit(self.driver3_data)
        self.driver3_driver_age.setGeometry(QtCore.QRect(140, 110, 131, 22))
        self.driver3_driver_age.setObjectName("driver3_driver_age")
        self.label_38 = QtWidgets.QLabel(self.driver3_data)
        self.label_38.setGeometry(QtCore.QRect(190, 40, 31, 20))
        self.label_38.setObjectName("label_38")
        self.driver3_main_name = QtWidgets.QLineEdit(self.driver3_data)
        self.driver3_main_name.setGeometry(QtCore.QRect(140, 60, 131, 22))
        self.driver3_main_name.setObjectName("driver3_main_name")
        self.driver3_text_tip = QtWidgets.QTextBrowser(self.driver3_data)
        self.driver3_text_tip.setGeometry(QtCore.QRect(0, 0, 81, 31))
        self.driver3_text_tip.setObjectName("driver3_text_tip")
        self.driver3_child = QtWidgets.QComboBox(self.driver3_data)
        self.driver3_child.setGeometry(QtCore.QRect(290, 110, 131, 22))
        self.driver3_child.setObjectName("driver3_child")
        self.driver3_child.addItem("")
        self.driver3_child.addItem("")
        self.label_39 = QtWidgets.QLabel(self.driver3_data)
        self.label_39.setGeometry(QtCore.QRect(340, 90, 41, 16))
        self.label_39.setObjectName("label_39")
        self.driver3_status = QtWidgets.QComboBox(self.driver3_data)
        self.driver3_status.setGeometry(QtCore.QRect(450, 60, 131, 22))
        self.driver3_status.setObjectName("driver3_status")
        self.driver3_status.addItem("")
        self.driver3_status.addItem("")
        self.label_40 = QtWidgets.QLabel(self.driver3_data)
        self.label_40.setGeometry(QtCore.QRect(470, 40, 101, 16))
        self.label_40.setObjectName("label_40")
        self.driver3_license_number = QtWidgets.QLineEdit(self.driver3_data)
        self.driver3_license_number.setGeometry(QtCore.QRect(430, 110, 71, 22))
        self.driver3_license_number.setObjectName("driver3_license_number")
        self.driver3_license_series = QtWidgets.QLineEdit(self.driver3_data)
        self.driver3_license_series.setGeometry(QtCore.QRect(520, 110, 101, 22))
        self.driver3_license_series.setObjectName("driver3_license_series")
        self.label_41 = QtWidgets.QLabel(self.driver3_data)
        self.label_41.setGeometry(QtCore.QRect(460, 90, 111, 16))
        self.label_41.setObjectName("label_41")
        self.driver4_data = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.driver4_data.setEnabled(False)
        self.driver4_data.setGeometry(QtCore.QRect(10, 1060, 671, 191))
        self.driver4_data.setStyleSheet("")
        self.driver4_data.setObjectName("driver4_data")
        self.driver4_owner = QtWidgets.QCheckBox(self.driver4_data)
        self.driver4_owner.setGeometry(QtCore.QRect(260, 140, 181, 20))
        self.driver4_owner.setObjectName("driver4_owner")
        self.label_42 = QtWidgets.QLabel(self.driver4_data)
        self.label_42.setGeometry(QtCore.QRect(40, 40, 61, 16))
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.driver4_data)
        self.label_43.setGeometry(QtCore.QRect(190, 90, 31, 20))
        self.label_43.setObjectName("label_43")
        self.driver4_middle_name = QtWidgets.QLineEdit(self.driver4_data)
        self.driver4_middle_name.setGeometry(QtCore.QRect(290, 60, 131, 22))
        self.driver4_middle_name.setObjectName("driver4_middle_name")
        self.label_44 = QtWidgets.QLabel(self.driver4_data)
        self.label_44.setGeometry(QtCore.QRect(330, 40, 55, 21))
        self.label_44.setObjectName("label_44")
        self.driver4_birthday_date = QtWidgets.QLineEdit(self.driver4_data)
        self.driver4_birthday_date.setGeometry(QtCore.QRect(0, 110, 131, 22))
        self.driver4_birthday_date.setObjectName("driver4_birthday_date")
        self.driver4_last_name = QtWidgets.QLineEdit(self.driver4_data)
        self.driver4_last_name.setGeometry(QtCore.QRect(0, 60, 131, 22))
        self.driver4_last_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.driver4_last_name.setObjectName("driver4_last_name")
        self.label_45 = QtWidgets.QLabel(self.driver4_data)
        self.label_45.setGeometry(QtCore.QRect(50, 90, 21, 20))
        self.label_45.setObjectName("label_45")
        self.driver4_insured = QtWidgets.QCheckBox(self.driver4_data)
        self.driver4_insured.setGeometry(QtCore.QRect(20, 140, 181, 20))
        self.driver4_insured.setObjectName("driver4_insured")
        self.driver4_driver_age = QtWidgets.QLineEdit(self.driver4_data)
        self.driver4_driver_age.setGeometry(QtCore.QRect(140, 110, 131, 22))
        self.driver4_driver_age.setObjectName("driver4_driver_age")
        self.label_46 = QtWidgets.QLabel(self.driver4_data)
        self.label_46.setGeometry(QtCore.QRect(190, 40, 31, 20))
        self.label_46.setObjectName("label_46")
        self.driver4_main_name = QtWidgets.QLineEdit(self.driver4_data)
        self.driver4_main_name.setGeometry(QtCore.QRect(140, 60, 131, 22))
        self.driver4_main_name.setObjectName("driver4_main_name")
        self.driver4_text_tip = QtWidgets.QTextBrowser(self.driver4_data)
        self.driver4_text_tip.setGeometry(QtCore.QRect(0, 0, 81, 31))
        self.driver4_text_tip.setObjectName("driver4_text_tip")
        self.driver4_child = QtWidgets.QComboBox(self.driver4_data)
        self.driver4_child.setGeometry(QtCore.QRect(290, 110, 131, 22))
        self.driver4_child.setObjectName("driver4_child")
        self.driver4_child.addItem("")
        self.driver4_child.addItem("")
        self.label_47 = QtWidgets.QLabel(self.driver4_data)
        self.label_47.setGeometry(QtCore.QRect(340, 90, 41, 16))
        self.label_47.setObjectName("label_47")
        self.driver4_status = QtWidgets.QComboBox(self.driver4_data)
        self.driver4_status.setGeometry(QtCore.QRect(450, 60, 131, 22))
        self.driver4_status.setObjectName("driver4_status")
        self.driver4_status.addItem("")
        self.driver4_status.addItem("")
        self.label_48 = QtWidgets.QLabel(self.driver4_data)
        self.label_48.setGeometry(QtCore.QRect(470, 40, 101, 16))
        self.label_48.setObjectName("label_48")
        self.driver4_license_number = QtWidgets.QLineEdit(self.driver4_data)
        self.driver4_license_number.setGeometry(QtCore.QRect(430, 110, 71, 22))
        self.driver4_license_number.setObjectName("driver4_license_number")
        self.driver4_license_series4 = QtWidgets.QLineEdit(self.driver4_data)
        self.driver4_license_series4.setGeometry(QtCore.QRect(520, 110, 101, 22))
        self.driver4_license_series4.setObjectName("driver4_license_series4")
        self.label_49 = QtWidgets.QLabel(self.driver4_data)
        self.label_49.setGeometry(QtCore.QRect(460, 90, 111, 16))
        self.label_49.setObjectName("label_49")
        self.driver5_data = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.driver5_data.setEnabled(False)
        self.driver5_data.setGeometry(QtCore.QRect(10, 1290, 671, 231))
        self.driver5_data.setStyleSheet("")
        self.driver5_data.setObjectName("driver5_data")
        self.driver5_owner = QtWidgets.QCheckBox(self.driver5_data)
        self.driver5_owner.setGeometry(QtCore.QRect(260, 140, 181, 20))
        self.driver5_owner.setObjectName("driver5_owner")
        self.label_50 = QtWidgets.QLabel(self.driver5_data)
        self.label_50.setGeometry(QtCore.QRect(40, 40, 61, 16))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.driver5_data)
        self.label_51.setGeometry(QtCore.QRect(190, 90, 31, 20))
        self.label_51.setObjectName("label_51")
        self.driver5_middle_name = QtWidgets.QLineEdit(self.driver5_data)
        self.driver5_middle_name.setGeometry(QtCore.QRect(290, 60, 131, 22))
        self.driver5_middle_name.setObjectName("driver5_middle_name")
        self.label_52 = QtWidgets.QLabel(self.driver5_data)
        self.label_52.setGeometry(QtCore.QRect(330, 40, 55, 21))
        self.label_52.setObjectName("label_52")
        self.driver5_birthday_date = QtWidgets.QLineEdit(self.driver5_data)
        self.driver5_birthday_date.setGeometry(QtCore.QRect(0, 110, 131, 22))
        self.driver5_birthday_date.setObjectName("driver5_birthday_date")
        self.driver5_last_name = QtWidgets.QLineEdit(self.driver5_data)
        self.driver5_last_name.setGeometry(QtCore.QRect(0, 60, 131, 22))
        self.driver5_last_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.driver5_last_name.setObjectName("driver5_last_name")
        self.label_53 = QtWidgets.QLabel(self.driver5_data)
        self.label_53.setGeometry(QtCore.QRect(50, 90, 21, 20))
        self.label_53.setObjectName("label_53")
        self.driver5_insured = QtWidgets.QCheckBox(self.driver5_data)
        self.driver5_insured.setGeometry(QtCore.QRect(20, 140, 181, 20))
        self.driver5_insured.setObjectName("driver5_insured")
        self.driver5_driver_age = QtWidgets.QLineEdit(self.driver5_data)
        self.driver5_driver_age.setGeometry(QtCore.QRect(140, 110, 131, 22))
        self.driver5_driver_age.setObjectName("driver5_driver_age")
        self.label_54 = QtWidgets.QLabel(self.driver5_data)
        self.label_54.setGeometry(QtCore.QRect(190, 40, 31, 20))
        self.label_54.setObjectName("label_54")
        self.driver5_main_name = QtWidgets.QLineEdit(self.driver5_data)
        self.driver5_main_name.setGeometry(QtCore.QRect(140, 60, 131, 22))
        self.driver5_main_name.setObjectName("driver5_main_name")
        self.driver5_text_tip = QtWidgets.QTextBrowser(self.driver5_data)
        self.driver5_text_tip.setGeometry(QtCore.QRect(0, 0, 81, 31))
        self.driver5_text_tip.setObjectName("driver5_text_tip")
        self.driver5_child = QtWidgets.QComboBox(self.driver5_data)
        self.driver5_child.setGeometry(QtCore.QRect(290, 110, 131, 22))
        self.driver5_child.setObjectName("driver5_child")
        self.driver5_child.addItem("")
        self.driver5_child.addItem("")
        self.label_55 = QtWidgets.QLabel(self.driver5_data)
        self.label_55.setGeometry(QtCore.QRect(340, 90, 41, 16))
        self.label_55.setObjectName("label_55")
        self.driver5_status = QtWidgets.QComboBox(self.driver5_data)
        self.driver5_status.setGeometry(QtCore.QRect(450, 60, 131, 22))
        self.driver5_status.setObjectName("driver5_status")
        self.driver5_status.addItem("")
        self.driver5_status.addItem("")
        self.label_56 = QtWidgets.QLabel(self.driver5_data)
        self.label_56.setGeometry(QtCore.QRect(470, 40, 101, 16))
        self.label_56.setObjectName("label_56")
        self.driver5_license_number = QtWidgets.QLineEdit(self.driver5_data)
        self.driver5_license_number.setGeometry(QtCore.QRect(430, 110, 71, 22))
        self.driver5_license_number.setObjectName("driver5_license_number")
        self.driver5_license_series = QtWidgets.QLineEdit(self.driver5_data)
        self.driver5_license_series.setGeometry(QtCore.QRect(520, 110, 101, 22))
        self.driver5_license_series.setObjectName("driver5_license_series")
        self.label_57 = QtWidgets.QLabel(self.driver5_data)
        self.label_57.setGeometry(QtCore.QRect(460, 90, 111, 16))
        self.label_57.setObjectName("label_57")
        self.anketa_menu = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.anketa_menu.setGeometry(QtCore.QRect(10, 1520, 671, 161))
        self.anketa_menu.setStyleSheet("")
        self.anketa_menu.setObjectName("anketa_menu")
        self.calc_start = QtWidgets.QPushButton(self.anketa_menu)
        self.calc_start.setGeometry(QtCore.QRect(20, 100, 211, 31))
        self.calc_start.setObjectName("calc_start")
        self.save_data = QtWidgets.QPushButton(self.anketa_menu)
        self.save_data.setGeometry(QtCore.QRect(20, 60, 211, 31))
        self.save_data.setObjectName("save_data")
        self.back_to_main = QtWidgets.QPushButton(self.anketa_menu)
        self.back_to_main.setGeometry(QtCore.QRect(250, 100, 191, 31))
        self.back_to_main.setObjectName("back_to_main")
        self.send_phone_number = QtWidgets.QPushButton(self.anketa_menu)
        self.send_phone_number.setGeometry(QtCore.QRect(250, 60, 191, 31))
        self.send_phone_number.setObjectName("send_phone_number")
        self.bypass_result = QtWidgets.QTextBrowser(self.anketa_menu)
        self.bypass_result.setGeometry(QtCore.QRect(460, 60, 191, 71))
        self.bypass_result.setObjectName("bypass_result")
        self.phone_number = QtWidgets.QLineEdit(self.anketa_menu)
        self.phone_number.setGeometry(QtCore.QRect(140, 20, 141, 22))
        self.phone_number.setObjectName("phone_number")
        self.label_7 = QtWidgets.QLabel(self.anketa_menu)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.anketa_menu)
        self.label_8.setGeometry(QtCore.QRect(120, 20, 20, 20))
        self.label_8.setObjectName("label_8")
        self.driver5_add_box = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.driver5_add_box.setGeometry(QtCore.QRect(10, 1260, 211, 20))
        self.driver5_add_box.setObjectName("driver5_add_box")
        self.driver4_add_box = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.driver4_add_box.setGeometry(QtCore.QRect(10, 1030, 221, 20))
        self.driver4_add_box.setObjectName("driver4_add_box")
        self.driver3_add_box = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.driver3_add_box.setGeometry(QtCore.QRect(10, 770, 211, 20))
        self.driver3_add_box.setObjectName("driver3_add_box")
        self.anketa_menu.raise_()
        self.checkBox.raise_()
        self.label_10.raise_()
        self.checkBox_5.raise_()
        self.grz.raise_()
        self.checkBox_4.raise_()
        self.label.raise_()
        self.checkBox_6.raise_()
        self.car_data.raise_()
        self.label_11.raise_()
        self.checkBox_2.raise_()
        self.label_9.raise_()
        self.driver1_data.raise_()
        self.checkBox_3.raise_()
        self.search_cl.raise_()
        self.driver2_data.raise_()
        self.driver3_data.raise_()
        self.driver4_data.raise_()
        self.driver5_data.raise_()
        self.driver5_add_box.raise_()
        self.driver4_add_box.raise_()
        self.driver3_add_box.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.label_10.setBuddy(self.grz)
        self.label.setBuddy(self.grz)
        self.label_11.setBuddy(self.grz)
        self.label_9.setBuddy(self.grz)
        self.label_2.setBuddy(self.driver1_last_name)
        self.label_5.setBuddy(self.driver1_driver_age)
        self.label_6.setBuddy(self.driver1_middle_name)
        self.label_3.setBuddy(self.driver1_birthday_date)
        self.label_4.setBuddy(self.driver1_main_name)
        self.label_15.setBuddy(self.grz)
        self.label_25.setBuddy(self.driver1_last_name)
        self.label_26.setBuddy(self.driver1_driver_age)
        self.label_27.setBuddy(self.driver1_middle_name)
        self.label_28.setBuddy(self.driver1_birthday_date)
        self.label_29.setBuddy(self.driver1_main_name)
        self.label_34.setBuddy(self.driver1_last_name)
        self.label_35.setBuddy(self.driver1_driver_age)
        self.label_36.setBuddy(self.driver1_middle_name)
        self.label_37.setBuddy(self.driver1_birthday_date)
        self.label_38.setBuddy(self.driver1_main_name)
        self.label_42.setBuddy(self.driver1_last_name)
        self.label_43.setBuddy(self.driver1_driver_age)
        self.label_44.setBuddy(self.driver1_middle_name)
        self.label_45.setBuddy(self.driver1_birthday_date)
        self.label_46.setBuddy(self.driver1_main_name)
        self.label_50.setBuddy(self.driver1_last_name)
        self.label_51.setBuddy(self.driver1_driver_age)
        self.label_52.setBuddy(self.driver1_middle_name)
        self.label_53.setBuddy(self.driver1_birthday_date)
        self.label_54.setBuddy(self.driver1_main_name)
        self.label_7.setBuddy(self.phone_number)
        self.label_8.setBuddy(self.phone_number)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.checkBox.setText(_translate("Dialog", "Новый ТС"))
        self.label_10.setText(_translate("Dialog", "Заполните анкету клиента"))
        self.checkBox_5.setText(_translate("Dialog", "Согласие"))
        self.checkBox_4.setText(_translate("Dialog", "Ренессанс"))
        self.label.setText(_translate("Dialog", "ГРЗ"))
        self.checkBox_6.setText(_translate("Dialog", "ВСК"))
        self.label_12.setText(_translate("Dialog", "Модель"))
        self.label_13.setText(_translate("Dialog", "Год выпуска"))
        self.label_14.setText(_translate("Dialog", "Марка"))
        self.label_16.setText(_translate("Dialog", "VIN"))
        self.label_17.setText(_translate("Dialog", "Мощность ( Л.С)"))
        self.label_18.setText(_translate("Dialog", "Кузов"))
        self.label_19.setText(_translate("Dialog", "Коробка"))
        self.car_transmission_type.setItemText(0, _translate("Dialog", "Автоматическая"))
        self.car_transmission_type.setItemText(1, _translate("Dialog", "Механическая"))
        self.car_body_type.setItemText(0, _translate("Dialog", "Седан"))
        self.car_body_type.setItemText(1, _translate("Dialog", "Хетчбек"))
        self.car_body_type.setItemText(2, _translate("Dialog", "Универсал"))
        self.car_body_type.setItemText(3, _translate("Dialog", "Внедорожник"))
        self.car_body_type.setItemText(4, _translate("Dialog", "Лифтбек"))
        self.car_engine_type.setItemText(0, _translate("Dialog", "Бензин"))
        self.car_engine_type.setItemText(1, _translate("Dialog", "Дизель"))
        self.label_20.setText(_translate("Dialog", "Тип двигателя"))
        self.label_24.setText(_translate("Dialog", "дата начала эксплуатации"))
        self.label_11.setText(_translate("Dialog", "Данные автомобиля"))
        self.checkBox_2.setText(_translate("Dialog", "Абсолют"))
        self.label_9.setText(_translate("Dialog", "В каких СК считаем?"))
        self.driver1_owner.setText(_translate("Dialog", "Является собственником"))
        self.label_2.setText(_translate("Dialog", "Фамилия"))
        self.label_5.setText(_translate("Dialog", "Стаж"))
        self.label_6.setText(_translate("Dialog", "Отчество"))
        self.label_3.setText(_translate("Dialog", "Д.Р"))
        self.driver1_insured.setText(_translate("Dialog", "Является страхователем"))
        self.label_4.setText(_translate("Dialog", "Имя"))
        self.driver1_text_tip.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Водитель 1</p></body></html>"))
        self.driver1_child.setItemText(0, _translate("Dialog", "Дети есть"))
        self.driver1_child.setItemText(1, _translate("Dialog", "Детей нет"))
        self.label_21.setText(_translate("Dialog", "Дети"))
        self.driver1_status.setItemText(0, _translate("Dialog", "В браке"))
        self.driver1_status.setItemText(1, _translate("Dialog", "Не в браке"))
        self.label_22.setText(_translate("Dialog", "Сем. положение"))
        self.label_23.setText(_translate("Dialog", "Серия и номер ВУ"))
        self.label_15.setText(_translate("Dialog", "Данные водителей:"))
        self.driver2_add_box.setText(_translate("Dialog", "Добавить/удалить водителя 2"))
        self.checkBox_3.setText(_translate("Dialog", "Тинькофф"))
        self.driver2_owner.setText(_translate("Dialog", "Является собственником"))
        self.label_25.setText(_translate("Dialog", "Фамилия"))
        self.label_26.setText(_translate("Dialog", "Стаж"))
        self.label_27.setText(_translate("Dialog", "Отчество"))
        self.label_28.setText(_translate("Dialog", "Д.Р"))
        self.driver2_insured.setText(_translate("Dialog", "Является страхователем"))
        self.label_29.setText(_translate("Dialog", "Имя"))
        self.driver2_text_tip.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Водитель 2</p></body></html>"))
        self.driver2_child.setItemText(0, _translate("Dialog", "Дети есть"))
        self.driver2_child.setItemText(1, _translate("Dialog", "Детей нет"))
        self.label_30.setText(_translate("Dialog", "Дети"))
        self.driver2_status.setItemText(0, _translate("Dialog", "В браке"))
        self.driver2_status.setItemText(1, _translate("Dialog", "Не в браке"))
        self.label_31.setText(_translate("Dialog", "Сем. положение"))
        self.label_32.setText(_translate("Dialog", "Серия и номер ВУ"))
        self.driver3_owner_3.setText(_translate("Dialog", "Является собственником"))
        self.label_34.setText(_translate("Dialog", "Фамилия"))
        self.label_35.setText(_translate("Dialog", "Стаж"))
        self.label_36.setText(_translate("Dialog", "Отчество"))
        self.label_37.setText(_translate("Dialog", "Д.Р"))
        self.driver3_insured.setText(_translate("Dialog", "Является страхователем"))
        self.label_38.setText(_translate("Dialog", "Имя"))
        self.driver3_text_tip.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Водитель 3</p></body></html>"))
        self.driver3_child.setItemText(0, _translate("Dialog", "Дети есть"))
        self.driver3_child.setItemText(1, _translate("Dialog", "Детей нет"))
        self.label_39.setText(_translate("Dialog", "Дети"))
        self.driver3_status.setItemText(0, _translate("Dialog", "В браке"))
        self.driver3_status.setItemText(1, _translate("Dialog", "Не в браке"))
        self.label_40.setText(_translate("Dialog", "Сем. положение"))
        self.label_41.setText(_translate("Dialog", "Серия и номер ВУ"))
        self.driver4_owner.setText(_translate("Dialog", "Является собственником"))
        self.label_42.setText(_translate("Dialog", "Фамилия"))
        self.label_43.setText(_translate("Dialog", "Стаж"))
        self.label_44.setText(_translate("Dialog", "Отчество"))
        self.label_45.setText(_translate("Dialog", "Д.Р"))
        self.driver4_insured.setText(_translate("Dialog", "Является страхователем"))
        self.label_46.setText(_translate("Dialog", "Имя"))
        self.driver4_text_tip.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Водитель 4</p></body></html>"))
        self.driver4_child.setItemText(0, _translate("Dialog", "Дети есть"))
        self.driver4_child.setItemText(1, _translate("Dialog", "Детей нет"))
        self.label_47.setText(_translate("Dialog", "Дети"))
        self.driver4_status.setItemText(0, _translate("Dialog", "В браке"))
        self.driver4_status.setItemText(1, _translate("Dialog", "Не в браке"))
        self.label_48.setText(_translate("Dialog", "Сем. положение"))
        self.label_49.setText(_translate("Dialog", "Серия и номер ВУ"))
        self.driver5_owner.setText(_translate("Dialog", "Является собственником"))
        self.label_50.setText(_translate("Dialog", "Фамилия"))
        self.label_51.setText(_translate("Dialog", "Стаж"))
        self.label_52.setText(_translate("Dialog", "Отчество"))
        self.label_53.setText(_translate("Dialog", "Д.Р"))
        self.driver5_insured.setText(_translate("Dialog", "Является страхователем"))
        self.label_54.setText(_translate("Dialog", "Имя"))
        self.driver5_text_tip.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Водитель 5</p></body></html>"))
        self.driver5_child.setItemText(0, _translate("Dialog", "Дети есть"))
        self.driver5_child.setItemText(1, _translate("Dialog", "Детей нет"))
        self.label_55.setText(_translate("Dialog", "Дети"))
        self.driver5_status.setItemText(0, _translate("Dialog", "В браке"))
        self.driver5_status.setItemText(1, _translate("Dialog", "Не в браке"))
        self.label_56.setText(_translate("Dialog", "Сем. положение"))
        self.label_57.setText(_translate("Dialog", "Серия и номер ВУ"))
        self.calc_start.setText(_translate("Dialog", "Начать расчёт"))
        self.save_data.setText(_translate("Dialog", "Сохранить данные"))
        self.back_to_main.setText(_translate("Dialog", "Назад"))
        self.send_phone_number.setText(_translate("Dialog", "Добавить в Bypass"))
        self.label_7.setText(_translate("Dialog", "Номер телефона"))
        self.label_8.setText(_translate("Dialog", "79"))
        self.driver5_add_box.setText(_translate("Dialog", "Добавить удалить водителя 5"))
        self.driver4_add_box.setText(_translate("Dialog", "Добавить/ удалить водителя 4"))
        self.driver3_add_box.setText(_translate("Dialog", "Добавить/удалить водителя 3"))
        self.search_cl.setText(_translate("Dialog", "Поиск клиента"))

