# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Searching(object):
    def setupUi(self, Searching):
        Searching.setObjectName("Searching")
        Searching.resize(690, 440)
        self.listView = QtWidgets.QListView(Searching)
        self.listView.setGeometry(QtCore.QRect(10, 10, 661, 411))
        self.listView.setObjectName("listView")
        self.pushButton = QtWidgets.QPushButton(Searching)
        self.pushButton.setGeometry(QtCore.QRect(40, 330, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.last_name = QtWidgets.QLineEdit(Searching)
        self.last_name.setGeometry(QtCore.QRect(30, 100, 113, 22))
        self.last_name.setObjectName("last_name")
        self.main_name = QtWidgets.QLineEdit(Searching)
        self.main_name.setGeometry(QtCore.QRect(30, 150, 113, 22))
        self.main_name.setObjectName("main_name")
        self.middle_name = QtWidgets.QLineEdit(Searching)
        self.middle_name.setGeometry(QtCore.QRect(30, 210, 113, 22))
        self.middle_name.setObjectName("middle_name")
        self.list = QtWidgets.QLineEdit(Searching)
        self.list.setGeometry(QtCore.QRect(30, 270, 113, 22))
        self.list.setObjectName("list")
        self.widget = QtWidgets.QWidget(Searching)
        self.widget.setGeometry(QtCore.QRect(200, 50, 441, 361))
        self.widget.setObjectName("widget")
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setGeometry(QtCore.QRect(40, 30, 381, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 110, 381, 61))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser_3.setGeometry(QtCore.QRect(40, 190, 381, 61))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setGeometry(QtCore.QRect(10, 210, 21, 20))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 290, 201, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 130, 21, 20))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 50, 21, 20))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.label = QtWidgets.QLabel(Searching)
        self.label.setGeometry(QtCore.QRect(60, 80, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Searching)
        self.label_2.setGeometry(QtCore.QRect(70, 130, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Searching)
        self.label_3.setGeometry(QtCore.QRect(60, 190, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Searching)
        self.label_4.setGeometry(QtCore.QRect(60, 250, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label.setBuddy(self.last_name)
        self.label_2.setBuddy(self.main_name)
        self.label_3.setBuddy(self.middle_name)
        self.label_4.setBuddy(self.list)

        self.retranslateUi(Searching)
        QtCore.QMetaObject.connectSlotsByName(Searching)
        Searching.setTabOrder(self.last_name, self.main_name)
        Searching.setTabOrder(self.main_name, self.middle_name)
        Searching.setTabOrder(self.middle_name, self.list)
        Searching.setTabOrder(self.list, self.listView)
        Searching.setTabOrder(self.listView, self.pushButton)
        Searching.setTabOrder(self.pushButton, self.textBrowser)
        Searching.setTabOrder(self.textBrowser, self.textBrowser_2)
        Searching.setTabOrder(self.textBrowser_2, self.textBrowser_3)
        Searching.setTabOrder(self.textBrowser_3, self.checkBox)
        Searching.setTabOrder(self.checkBox, self.pushButton_3)
        Searching.setTabOrder(self.pushButton_3, self.checkBox_2)
        Searching.setTabOrder(self.checkBox_2, self.checkBox_3)

    def retranslateUi(self, Searching):
        _translate = QtCore.QCoreApplication.translate
        Searching.setWindowTitle(_translate("Searching", "Dialog"))
        self.pushButton.setText(_translate("Searching", "Поиск"))
        self.pushButton_3.setText(_translate("Searching", "Выбрать клиента"))
        self.label.setText(_translate("Searching", "Фамилия"))
        self.label_2.setText(_translate("Searching", "Имя"))
        self.label_3.setText(_translate("Searching", "Отчество"))
        self.label_4.setText(_translate("Searching", "Договор"))
